# Generated by Django 6.0.3 on 2026-03-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('simulation_speed', models.FloatField(default=1.5)),
                ('failure_probability', models.FloatField(default=25.0)),
                ('recovery_rate', models.FloatField(default=60.0)),
                ('auto_recovery', models.BooleanField(default=True)),
                ('cascade_prevention', models.BooleanField(default=False)),
                ('total_ticks', models.IntegerField(default=50)),
                ('system_health', models.FloatField(default=100.0)),
                ('total_failures', models.IntegerField(default=0)),
                ('critical_nodes', models.IntegerField(default=0)),
                ('avg_recovery_time', models.FloatField(default=0.0)),
                ('timeline_data', models.JSONField(blank=True, default=dict)),
                ('risk_propagation_data', models.JSONField(blank=True, default=list)),
                ('node_snapshots', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FailureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField()),
                ('stability_before', models.FloatField()),
                ('stability_after', models.FloatField()),
                ('was_cascade', models.BooleanField(default=False)),
                ('recovered', models.BooleanField(default=False)),
                ('recovery_tick', models.IntegerField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_events', to='infrastructure.infrastructurenode')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_failures', to='infrastructure.infrastructurenode')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_events', to='simulation.simulationrun')),
            ],
            options={
                'ordering': ['tick'],
            },
        ),
    ]
