# Generated by Django 6.0.3 on 2026-03-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVERecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('NONE', 'None')], default='MEDIUM', max_length=10)),
                ('attack_vector', models.CharField(blank=True, max_length=50)),
                ('attack_complexity', models.CharField(blank=True, max_length=20)),
                ('privileges_required', models.CharField(blank=True, max_length=20)),
                ('user_interaction', models.CharField(blank=True, max_length=20)),
                ('scope', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('warning', 'Warning'), ('critical', 'Critical'), ('exploited', 'Exploited'), ('mitigated', 'Mitigated')], default='warning', max_length=20)),
                ('exploit_available', models.BooleanField(default=False)),
                ('patch_available', models.BooleanField(default=False)),
                ('affected_products', models.JSONField(default=list)),
                ('affected_vendors', models.JSONField(default=list)),
                ('cwe_ids', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CVE Record',
                'verbose_name_plural': 'CVE Records',
                'ordering': ['-cvss_score', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(default='nvd_api', max_length=50)),
                ('keywords', models.JSONField(default=list)),
                ('severity_filter', models.CharField(blank=True, max_length=20)),
                ('days_back', models.IntegerField(default=30)),
                ('total_found', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Scan Histories',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveField(
            model_name='failureevent',
            name='node',
        ),
        migrations.RemoveField(
            model_name='failureevent',
            name='simulation',
        ),
        migrations.RemoveField(
            model_name='failureevent',
            name='triggered_by',
        ),
        migrations.CreateModel(
            name='MitigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('patch', 'Apply Patch'), ('isolate', 'Isolate System'), ('block', 'Block Attack Vector'), ('monitor', 'Enhanced Monitoring'), ('script', 'Run Remediation Script')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('risk_reduction', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='simulation.cverecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SimulationRun',
        ),
        migrations.DeleteModel(
            name='FailureEvent',
        ),
    ]
