# Generated by Django 6.0.3 on 2026-04-02 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_cverecord_scanhistory_remove_failureevent_node_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('info', 'Info')], default='info', max_length=20)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alert_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('os_type', models.CharField(blank=True, default='', max_length=100)),
                ('os_version', models.CharField(blank=True, default='', max_length=100)),
                ('services', models.JSONField(default=list)),
                ('criticality', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development')], default='production', max_length=20)),
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('internet_facing', models.BooleanField(default=False)),
                ('behind_firewall', models.BooleanField(default=True)),
                ('requires_vpn', models.BooleanField(default=False)),
                ('last_scanned', models.DateTimeField(auto_now=True)),
                ('scan_method', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Asset Inventory',
                'db_table': 'asset_inventory',
                'ordering': ['-criticality', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_cves', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('avg_risk', models.FloatField(default=0)),
                ('system_health', models.IntegerField(default=100)),
                ('entry_points', models.IntegerField(default=0)),
                ('assets_scanned', models.IntegerField(default=0)),
                ('asset_matches', models.IntegerField(default=0)),
                ('exploit_count', models.IntegerField(default=0)),
                ('compliance_score', models.IntegerField(default=100)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'risk_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.JSONField(default=list)),
                ('rate_limit', models.IntegerField(default=100)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('analyst', 'Security Analyst'), ('viewer', 'Viewer'), ('api_user', 'API User')], default='viewer', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('api_key_created', models.DateTimeField(blank=True, null=True)),
                ('allowed_actions', models.JSONField(default=list)),
                ('notification_preferences', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='CVEAssetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_product', models.CharField(max_length=255)),
                ('matched_service', models.JSONField(default=dict)),
                ('confidence_score', models.IntegerField(default=0)),
                ('is_exploitable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='simulation.assetinventory')),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_mappings', to='simulation.cverecord')),
            ],
            options={
                'db_table': 'cve_asset_mapping',
                'unique_together': {('cve', 'asset', 'matched_product')},
            },
        ),
    ]
