# Generated by Django 6.0.3 on 2026-04-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_alertrecord_assetinventory_risksnapshot_apikey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risksnapshot',
            name='compliance_score',
        ),
        migrations.AddField(
            model_name='cveassetmapping',
            name='match_type',
            field=models.CharField(default='product_match', max_length=50),
        ),
        migrations.AlterField(
            model_name='alertrecord',
            name='alert_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alertrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alertrecord',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='alertrecord',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='risksnapshot',
            name='avg_risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='risksnapshot',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='risksnapshot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='risksnapshot',
            index=models.Index(fields=['-timestamp'], name='risk_snapsh_timesta_a342b7_idx'),
        ),
    ]
