# Generated by Django 6.0.3 on 2026-04-20 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_alter_cverecord_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # WebhookDelivery already exists in DB — use SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='WebhookDelivery',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('integration_name', models.CharField(max_length=100)),
                        ('integration_type', models.CharField(default='webhook', max_length=20)),
                        ('event_type', models.CharField(max_length=100)),
                        ('event_title', models.CharField(blank=True, max_length=255)),
                        ('severity', models.CharField(default='info', max_length=20)),
                        ('payload', models.JSONField(default=dict)),
                        ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                        ('status_code', models.IntegerField(blank=True, null=True)),
                        ('response_preview', models.TextField(blank=True)),
                        ('error_message', models.TextField(blank=True)),
                        ('delivered_at', models.DateTimeField(auto_now_add=True)),
                        ('duration_ms', models.IntegerField(blank=True, null=True)),
                    ],
                    options={
                        'ordering': ['-delivered_at'],
                    },
                ),
            ],
            database_operations=[
                # Table already exists — do nothing
            ],
        ),

        # IntegrationConfig already exists in DB — use SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='IntegrationConfig',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('integration_type', models.CharField(choices=[('slack', 'Slack'), ('jira', 'Jira'), ('pagerduty', 'PagerDuty'), ('webhook', 'Webhook')], max_length=20)),
                        ('name', models.CharField(max_length=100)),
                        ('config_data', models.JSONField(default=dict)),
                        ('is_enabled', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_configs', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'unique_together': {('integration_type', 'name')},
                    },
                ),
            ],
            database_operations=[
                # Table already exists — do nothing
            ],
        ),

        # These are new columns — safe to add normally
        migrations.AddField(
            model_name='alertrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
