# Generated by Django 6.0.3 on 2026-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0008_add_owner_to_asset_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cverecord',
            name='epss_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cverecord',
            name='epss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cverecord',
            name='epss_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
