# Generated by Django 6.0.3 on 2026-03-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('gateway', 'Gateway / Load Balancer'), ('server', 'Application Server'), ('database', 'Database'), ('network', 'Network / Switch'), ('cache', 'Cache Layer'), ('queue', 'Message Queue'), ('cdn', 'CDN Edge Node')], max_length=20)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('warning', 'Warning'), ('critical', 'Critical'), ('failed', 'Failed')], default='operational', max_length=20)),
                ('stability', models.FloatField(default=100.0)),
                ('risk', models.FloatField(default=0.0)),
                ('max_load', models.FloatField(default=100.0)),
                ('current_load', models.FloatField(default=0.0)),
                ('failure_threshold', models.FloatField(default=20.0)),
                ('recovery_time', models.FloatField(default=5.0)),
                ('is_critical', models.BooleanField(default=False)),
                ('tier', models.IntegerField(default=0)),
                ('position_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tier', 'position_index'],
            },
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('depends_on', 'Depends On'), ('feeds_into', 'Feeds Into'), ('replicates_to', 'Replicates To'), ('load_balances', 'Load Balances')], default='depends_on', max_length=20)),
                ('bandwidth', models.FloatField(default=100.0)),
                ('latency', models.FloatField(default=1.0)),
                ('risk_propagation_factor', models.FloatField(default=0.5)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='infrastructure.infrastructurenode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='infrastructure.infrastructurenode')),
            ],
            options={
                'unique_together': {('source_node', 'target_node')},
            },
        ),
    ]
