# Generated by Django 6.0.3 on 2026-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealWorldScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source', models.CharField(help_text='e.g., Fastly 2021, AWS us-east-1', max_length=100)),
                ('year', models.IntegerField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('catastrophic', 'Catastrophic')], max_length=20)),
                ('config', models.JSONField(help_text='Configuration to load nodes and connections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='infrastructurenode',
            name='failure_threshold',
        ),
        migrations.RemoveField(
            model_name='infrastructurenode',
            name='recovery_time',
        ),
        migrations.RemoveField(
            model_name='nodeconnection',
            name='bandwidth',
        ),
        migrations.RemoveField(
            model_name='nodeconnection',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='nodeconnection',
            name='latency',
        ),
        migrations.AlterField(
            model_name='nodeconnection',
            name='risk_propagation_factor',
            field=models.FloatField(default=0.6),
        ),
    ]
